app:
  application_name: "Backtest Code"
  default_user: "score_ml_vs_if_mw"
  default_mode: "research"
  auto_open_plot: false

user:
  name: "score_ml_vs_if_mw"

paths:
  screen: 'C:/GoogleDrive/TP/00_screen/screen_aggregate.parquet'
  returns: 'C:/GoogleDrive/TP/00_screen/returns.parquet'
  liste_noire: ""
  output_dir: ""
  score_pivot_esg_path: ""

run:
  mode: "research"
  ptf_name: "Score ML vs IF MSCI World 20"
  bench: "MSCI WORLD"
  metrics:
    - "Score ML"
  percentile: 0.2
  top: true
  ponderation: "Racine cube"
  esg_exclusion: 0.0
  cut_mkt_cap: 0.0
  reco_secto: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  reco_facto: [0.0, 0.0, 0.0, 0.0, 0.0]
  score_neutral: "ICB 19"
  weight_neutral: "ICB 19"
  top_mandatory: null
  cap_weight_threshold: null
  score_pivot_esg: null
  mode_monthly_prod: false
  start_date: "2010-06-30"
  freq_rebal: null
  screen_start_date: "mois_impair"
  fill_method: "drift"
  max_weight: 1.0
  sector_neutral: false

batch:
  benches:
    - "MSCI WORLD"
  metrics:
    - "Score ML"
    - "Score ML_IF"
  percentiles:
    - 0.2
  start_dates:
    - "2010-06-30"
  top_values:
    - true
    - false
