export const PHASES = [
  ['submitted', '已提交'],
  ['running', '运行中'],
  ['evidence', '等证据'],
  ['done', '完成'],
]

export const DEFAULT_PIPELINE_PAYLOAD = {
  step: 'run_all',
  input_month: '',
  as_of: '',
  update_mode: 'both',
  flags: ['skip_refresh', 'skip_backtest', 'dry_run_data', 'inspect_backtest'],
  top_pct: 0.1,
  ml_weight: 0.7,
  technical_weight: 0.3,
  max_weight: 0.05,
  optimizer_method: 'constrained',
  portfolio_region: '',
  backtest_profile: 'default',
  bench: '',
  start_date: '',
  percentile: null,
}

export const EMPTY_JOB = {
  job_id: '',
  step: '暂无启动任务',
  status: 'idle',
  status_label: 'IDLE',
  phase: 'submitted',
  pid: '',
  started_at: '',
  manifest_status: 'N/A',
  manifest: '',
  log_path: '',
  log_tail: '',
  backend: '',
  queue_name: '',
  queued_at: '',
  status_updated_at: '',
  finished_at: '',
  returncode: '',
  error: '',
}

export const EMPTY_DASHBOARD_STATE = {
  generated_at: '',
  overview: [],
  latest_market_brief: {
    status: 'missing',
    title: '',
    created: '',
    source_scope: '',
    okf_refresh: '',
    path: '',
    okf_path: '',
    updated_at: '',
    sections: [],
    section_count: '0',
  },
  alerts: [],
  projects: [],
  assets: [],
  core_database: [],
  pipeline: [],
  signals: {
    regime: {
      status: 'missing',
      latest_date: '',
      updated_at: '',
      signal_path: '',
      rows: [],
      history: [],
      models: {
        status: 'missing',
        updated_at: '',
        state_models: [],
        risk_models: [],
        direction_models: [],
        volatility_models: [],
        drawdown_models: [],
      },
      message: '',
    },
    country: {
      status: 'missing',
      latest_date: '',
      updated_at: '',
      signal_path: '',
      database_path: '',
      single_country_path: '',
      rows: [],
      history: [],
      single_country_rows: [],
      single_country_history: [],
      message: '',
    },
    sector: {
      status: 'missing',
      latest_date: '',
      updated_at: '',
      paths: {},
      monthly_report: {
        status: 'missing',
        month: '',
        path: '',
        sectors: '0',
        updated_at: '',
      },
      rotation: {
        status: 'missing',
        latest_date: '',
        methodology: '',
        benchmark: '',
        markets: [],
      },
      markets: [],
      rows: [],
      message: '',
    },
    technical: {
      status: 'missing',
      latest_date: '',
      screen_date: '',
      pattern_date: '',
      period_end: '',
      available_date: '',
      updated_at: '',
      signal_path: '',
      screen_path: '',
      availability_note: '',
      metric_definitions: [],
      markets: [],
      metric_rows: [],
      security_rows: [],
      message: '',
    },
    score_ml_components: {
      status: 'missing',
      selected_date: '',
      selected_side: 'top',
      default_date: '',
      default_side: 'top',
      date_options: [],
      rows: [],
      run_dir: '',
      screen_date: '',
      message: '',
    },
  },
  queue: {
    queue_name: '',
    thread_worker_alive: false,
    in_memory_pending: 0,
    total_records: 0,
    counts: {
      queued: 0,
      running: 0,
      completed: 0,
      failed: 0,
      other: 0,
    },
    latest_job_id: '',
    recent: [],
  },
}

export function normalizeDashboardState(nextState = {}) {
  return {
    ...EMPTY_DASHBOARD_STATE,
    ...nextState,
    queue: {
      ...EMPTY_DASHBOARD_STATE.queue,
      ...(nextState.queue || {}),
      counts: {
        ...EMPTY_DASHBOARD_STATE.queue.counts,
        ...(nextState.queue?.counts || {}),
      },
    },
    signals: {
      ...EMPTY_DASHBOARD_STATE.signals,
      ...(nextState.signals || {}),
    },
  }
}
